DROP TABLE IF EXISTS `Raspberry`;
DROP TABLE IF EXISTS `Locker`;
DROP TABLE IF EXISTS `Ip`;

CREATE TABLE Raspberry (
    id INT PRIMARY KEY AUTO_INCREMENT,
    ip VARCHAR(255) NOT NULL
);

CREATE TABLE Locker (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    pin INT NOT NULL,
    close_or_open BOOLEAN NOT NULL,
    ip_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ip_id) REFERENCES Raspberry(id)
);
